---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: "node1.example.com"
localAPIEndpoint:
  advertiseAddress: "192.168.10.10"
  bindPort: 6443
bootstrapTokens:
  - token: "abcdef.0123456789abcdef"
    ttl: "24h0m0s"
    description: "bootstrap token"
    usages:
      - authentication
      - signing
    groups:
      - system:bootstrappers:kubeadm:default-node-token
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.30.0
networking:
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.96.0.0/16"
  dnsDomain: "cluster.local"
controlPlaneEndpoint: "192.168.10.10:6443"